14
rsa1971/libpythonpro pull request #18
Opened 2020-09-21 00:10 UTC by rsa1971

2020-09-24 11:08 UTC, wfoschiera requested changes

2020-09-25 01:28 UTC, wfoschiera commented
Recomendo excluir esse PR e aceitar o outro PR 14.

2020-09-25 15:56 UTC, rsa1971 commented
Boa tarde, Foschiera.
Veja se entendi. Apagar na figura abaixo:
1) #14
2) Update.gitignore
3) Update.requeriments.tex

Restará apenas a última linha com #14. É isso?


[cid:93d42fc9-d607-4473-8279-f349b795759b]


Grato,
Prof. Me. Renato Silva

________________________________
De: William Foschiera <notifications@github.com>
Enviado: sexta-feira, 25 de setembro de 2020 01:28
Para: rsa1971/libpythonpro <libpythonpro@noreply.github.com>
Cc: rsa1971 <prof.renatao@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [rsa1971/libpythonpro] 14 (#18)


Recomendo excluir esse PR e aceitar o outro PR 14.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/rsa1971/libpythonpro/pull/18#issuecomment-698670483>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQIWRSPK3UGU7J6YRKW4VPTSHPW45ANCNFSM4RT5ZEXA>.

2020-09-26 22:54 UTC, closed without merging

2020-09-26 22:57 UTC, rsa1971 commented
Fechando porque está antigo. Outro será aberto.